# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeyondSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
     pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'SwiftLint'
    pod 'ObjectMapper', '~> 3.3'
  # Pods for BeyondSwift

  target 'BeyondSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeyondSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
